// Lista de ícones disponíveis do Lucide para seleção no CMS
export const ICON_OPTIONS = [
  { value: "Heart", title: "Coração" },
  { value: "Users", title: "Usuários/Pessoas" },
  { value: "Book", title: "Livro" },
  { value: "BookOpen", title: "Livro Aberto" },
  { value: "Music", title: "Música" },
  { value: "Award", title: "Prêmio/Medalha" },
  { value: "Star", title: "Estrela" },
  { value: "Target", title: "Alvo/Meta" },
  { value: "TrendingUp", title: "Crescimento" },
  { value: "Globe", title: "Globo/Mundial" },
  { value: "MapPin", title: "Localização" },
  { value: "Home", title: "Casa" },
  { value: "School", title: "Escola" },
  { value: "GraduationCap", title: "Formatura/Educação" },
  { value: "Lightbulb", title: "Lâmpada/Ideia" },
  { value: "Sparkles", title: "Brilhos/Magia" },
  { value: "Rocket", title: "Foguete" },
  { value: "Calendar", title: "Calendário" },
  { value: "Clock", title: "Relógio" },
  { value: "CheckCircle", title: "Check/Confirmado" },
  { value: "Smile", title: "Sorriso" },
  { value: "ThumbsUp", title: "Curtir/Positivo" },
  { value: "Zap", title: "Raio/Energia" },
  { value: "Gift", title: "Presente" },
  { value: "Palette", title: "Paleta de Cores/Arte" },
  { value: "Camera", title: "Câmera" },
  { value: "Film", title: "Filme/Vídeo" },
  { value: "Mic", title: "Microfone" },
  { value: "Headphones", title: "Fones/Áudio" },
  { value: "Coffee", title: "Café/Pausa" },
];
